<?php

	declare(strict_types=1);

	namespace Sharkord\Builders;

	use Sharkord\Models\User;

	/**
	 * Class MessageBuilder
	 *
	 * Provides a fluent interface for constructing a message with optional
	 * file attachments before handing it off to a channel for dispatch.
	 *
	 * Build a message with {@see MessageBuilder::create()}, configure it with
	 * the fluent setters, then pass the instance directly to
	 * {@see \Sharkord\Models\Channel::sendMessage()}. Each queued file is read
	 * synchronously when the message is sent; the HTTP uploads are then dispatched
	 * concurrently. The builder is channel-agnostic until that point and can be
	 * prepared ahead of time or reused across multiple sends.
	 *
	 * @package Sharkord\Builders
	 *
	 * @example
	 * ```php
	 * $builder = \Sharkord\Builders\MessageBuilder::create()
	 *     ->setContent('Here are your files!')
	 *     ->addFile('/tmp/photo.jpg')
	 *     ->addFile('/tmp/report.pdf', 'application/pdf');
	 *
	 * $sharkord->channels->get('media')->sendMessage($builder);
	 * ```
	 *
	 * @example
	 * ```php
	 * // Build once, send to multiple channels.
	 * $sharkord->on(\Sharkord\Events::MESSAGE_CREATE, function(\Sharkord\Models\Message $message) {
	 *     if ($message->content === '!logs') {
	 *         $builder = \Sharkord\Builders\MessageBuilder::create()
	 *             ->setContent('Latest log file:')
	 *             ->addFile('/var/log/app.log', 'text/plain');
	 *
	 *         $message->channel->sendMessage($builder)
	 *             ->catch(function(\Throwable $e) use ($message) {
	 *                 $message->channel->sendMessage("Could not attach log: {$e->getMessage()}");
	 *             });
	 *     }
	 * });
	 * ```
	 */
	class MessageBuilder {

		/**
		 * @var string The message body text.
		 */
		private string $content = '';

		/**
		 * @var User|null The user to mention at the start of the message, or null for no mention.
		 */
		private ?User $replyUser = null;

		/**
		 * @var array<int, array{path: string, mime: string|null}> Queued file paths and optional MIME overrides.
		 */
		private array $pendingFiles = [];

		/**
		 * Creates a new MessageBuilder instance.
		 *
		 * Use this static factory rather than `new MessageBuilder()` to enable
		 * a fully fluent one-liner construction style.
		 *
		 * @return static
		 *
		 * @example
		 * ```php
		 * $builder = \Sharkord\Builders\MessageBuilder::create()
		 *     ->setContent('Hello!')
		 *     ->addFile('/tmp/file.txt');
		 * ```
		 */
		public static function create(): static {

			return new static();

		}

		/**
		 * Sets the message body text.
		 *
		 * @param string $content The message content.
		 * @return static Returns the builder instance for method chaining.
		 *
		 * @example
		 * ```php
		 * \Sharkord\Builders\MessageBuilder::create()->setContent('Hello, world!');
		 * ```
		 */
		public function setContent(string $content): static {

			$this->content = $content;

			return $this;

		}

		/**
		 * Queues a local file to be uploaded and attached to the message.
		 *
		 * Files are not uploaded until the builder is passed to
		 * {@see \Sharkord\Models\Channel::sendMessage()}. Each file is read
		 * synchronously at that point; the resulting HTTP uploads are then
		 * dispatched concurrently. Multiple calls append files in the order they
		 * are added. The MIME type is detected
		 * automatically via mime_content_type() when omitted; if detection fails,
		 * `application/octet-stream` is used as a safe fallback.
		 *
		 * @param string      $filePath The absolute or relative path to the file.
		 * @param string|null $mimeType MIME type override. Detected automatically when null.
		 * @return static Returns the builder instance for method chaining.
		 *
		 * @example
		 * ```php
		 * \Sharkord\Builders\MessageBuilder::create()
		 *     ->addFile('/tmp/image.png')
		 *     ->addFile('/tmp/data.csv', 'text/csv');
		 * ```
		 */
		public function addFile(string $filePath, ?string $mimeType = null): static {

			$this->pendingFiles[] = ['path' => $filePath, 'mime' => $mimeType];

			return $this;

		}

		/**
		 * Sets a user to be mentioned at the start of the message.
		 *
		 * Produces a mention span identical to the one generated by
		 * {@see \Sharkord\Models\Message::reply()}, prepended before the message
		 * content when the message is dispatched. The content set via setContent()
		 * is appended after the mention and is escaped normally.
		 *
		 * @param User $user The user to mention.
		 * @return static Returns the builder instance for method chaining.
		 *
		 * @example
		 * ```php
		 * $sharkord->on(\Sharkord\Events::MESSAGE_CREATE, function(\Sharkord\Models\Message $message) {
		 *     $builder = \Sharkord\Builders\MessageBuilder::create()
		 *         ->setReply($message->author)
		 *         ->setContent('Thanks for your message!')
		 *         ->addFile('/tmp/response.pdf');
		 *
		 *     $message->channel->sendMessage($builder);
		 * });
		 * ```
		 */
		public function setReply(User $user): static {

			$this->replyUser = $user;

			return $this;

		}

		/**
		 * Builds the final HTML string for the message body.
		 *
		 * If a reply user has been set via setReply(), a mention span is prepended
		 * before the escaped content. The result is always wrapped in a `<p>` tag,
		 * matching the wire format expected by the `messages.send` RPC.
		 *
		 * @return string The fully constructed HTML string ready for dispatch.
		 *
		 * @example
		 * ```php
		 * $builder = \Sharkord\Builders\MessageBuilder::create()->setContent('Hello!');
		 * echo $builder->buildHtml(); // "<p>Hello!</p>"
		 * ```
		 */
		public function buildHtml(): string {

			$escapedContent = htmlspecialchars($this->content, ENT_QUOTES, 'UTF-8');

			if ($this->replyUser === null) {
				return "<p>{$escapedContent}</p>";
			}

			$name    = htmlspecialchars($this->replyUser->name, ENT_QUOTES, 'UTF-8');
			$mention = "<span data-type=\"mention\" data-user-id=\"{$this->replyUser->id}\" class=\"mention\">@{$name}</span>";

			return "<p>{$mention} {$escapedContent}</p>";

		}

		/**
		 * Returns the message body text.
		 *
		 * @return string
		 *
		 * @example
		 * ```php
		 * $builder = \Sharkord\Builders\MessageBuilder::create()->setContent('Hello!');
		 * echo $builder->getContent(); // "Hello!"
		 * ```
		 */
		public function getContent(): string {

			return $this->content;

		}

		/**
		 * Returns the list of queued files.
		 *
		 * @return array<int, array{path: string, mime: string|null}>
		 *
		 * @example
		 * ```php
		 * $builder = \Sharkord\Builders\MessageBuilder::create()
		 *     ->addFile('/tmp/a.png')
		 *     ->addFile('/tmp/b.pdf', 'application/pdf');
		 *
		 * var_dump($builder->getPendingFiles());
		 * ```
		 */
		public function getPendingFiles(): array {

			return $this->pendingFiles;

		}

	}

?>